export const neighborhoods = [
  "Allerton",
  "Alphabet City",
  "Annadale",
  "Arden Heights",
  "Arlington",
  "Arrochar",
  "Arverne",
  "Astoria Heights",
  "Astoria",
  "Auburndale",
  "Bath Beach",
  "Bathgate",
  "Battery Park City",
  "Bay Ridge",
  "Bay Terrace",
  "Bay Terrace",
  "Baychester",
  "Bayside",
  "Bayswater",
  "Bedford Park",
  "Bedford Stuyvesant",
  "Beechhurst",
  "Beekman Place",
  "Bellaire",
  "Belle Harbor",
  "Bellerose",
  "Belmont",
  "Bensonhurst",
  "Bergen Beach",
  "Blissville",
  "Bloomfield",
  "Boerum Hill",
  "Borough Park",
  "Bowery",
  "Breezy Point",
  "Briarwood",
  "Brighton Beach",
  "Broad Channel",
  "Broadway Junction",
  "Bronx Park South",
  "Bronx River",
  "Bronxdale",
  "Brooklyn Heights",
  "Brookville",
  "Brownsville",
  "Bulls Head",
  "Bushwick",
  "Butler Manor",
  "Cambria Heights",
  "Canarsie",
  "Carnegie Hill",
  "Carroll Gardens",
  "Castle Hill",
  "Castleton Corners",
  "Charleston",
  "Chelsea",
  "Chinatown",
  "City Island",
  "City Line",
  "Civic Center",
  "Claremont Village",
  "Clason Point",
  "Clearview",
  "Clifton",
  "Clinton Hill",
  "Clinton",
  "Co-op City",
  "Cobble Hill",
  "College Point",
  "Concord",
  "Concourse Village",
  "Concourse",
  "Coney Island",
  "Country Club",
  "Crown Heights",
  "Cypress Hills",
  "Ditmas Park",
  "Dongan Hills",
  "Douglaston",
  "Downtown",
  "DUMBO",
  "Dutch Kills",
  "Dyker Heights",
  "East Elmhurst",
  "East Flatbush",
  "East Harlem",
  "East New York",
  "East Tremont",
  "East Village",
  "East Williamsburg",
  "Eastchester",
  "Edenwald",
  "Edgemere",
  "Edgewater Park",
  "Egbertville",
  "Elm Park",
  "Elmhurst",
  "Eltingville",
  "Emerson Hill",
  "Far Rockaway",
  "Farragut",
  "Fieldston",
  "Financial District",
  "Flatbush",
  "Flatiron",
  "Flatlands",
  "Floral Park",
  "Flushing (Downtown)",
  "Flushing",
  "Fordham",
  "Forest Hills Gardens",
  "Forest Hills",
  "Fort Greene",
  "Fort Hamilton",
  "Fox Hills",
  "Fresh Meadows",
  "Fulton Ferry",
  "Georgetown",
  "Gerritsen Beach",
  "Glen Oaks",
  "Glendale",
  "Gowanus",
  "Gramercy",
  "Graniteville",
  "Grant City",
  "Grasmere",
  "Gravesend",
  "Great Kills",
  "Greenpoint",
  "Greenridge",
  "Greenwich Village",
  "Grymes Hill",
  "Hamilton Heights",
  "Hammels",
  "Harlem (Central)",
  "Heartland Village",
  "Herald Square",
  "High Bridge",
  "Highland Park",
  "Hillcrest",
  "Hollis",
  "Holliswood",
  "Homecrest",
  "Howard Beach",
  "Howland Hook",
  "Hudson Square",
  "Huguenot",
  "Hunters Point",
  "Hunts Point",
  "Inwood",
  "Jackson Heights",
  "Jamaica Center",
  "Jamaica Estates",
  "Jamaica Hills",
  "Jamaica",
  "Kensington",
  "Kew Gardens Hills",
  "Kew Gardens",
  "Kings Highway",
  "Kingsbridge Heights",
  "Kingsbridge",
  "Kips Bay",
  "Laurelton",
  "Lefrak City",
  "Lenox Hill",
  "Lighthouse Hill",
  "Lincoln Square",
  "Lindenwood",
  "Little Italy",
  "Little Neck",
  "Little Ukraine",
  "Livingston",
  "Longwood",
  "Long Island City",
  "Lower East Side",
  "Manhattan Beach",
  "Manhattan Terrace",
  "Manhattan Valley",
  "Manhattanville",
  "Manor Heights",
  "Mapleton",
  "Marble Hill",
  "Marine Park",
  "Mariner's Harbor",
  "Maspeth",
  "Melrose",
  "Middle Village",
  "Midland Beach",
  "Midtown South",
  "Midtown",
  "Midwood",
  "Mill Basin",
  "Mill Island",
  "Morningside Heights",
  "Morris Heights",
  "Morris Park",
  "Morrisania",
  "Mott Haven",
  "Mount Eden",
  "Mount Hope",
  "Murray Hill",
  "Navy Yard",
  "Neponsit",
  "New Brighton",
  "New Dorp Beach",
  "New Dorp",
  "New Hyde Park",
  "New Springville",
  "NoHo",
  "North Corona",
  "North Riverdale",
  "Norwood",
  "Oakland Gardens",
  "Oakwood",
  "Ocean Hill",
  "Ocean Parkway",
  "Old Place",
  "Old Town",
  "Olinville",
  "Ozone Park",
  "Paerdegat Basin",
  "Park Hill",
  "Park Slope",
  "Parkchester",
  "Pelham Bay",
  "Pelham Gardens",
  "Pelham Parkway",
  "Pleasant Plains",
  "Plum Beach",
  "Pomonok",
  "Port Ivory",
  "Port Morris",
  "Port Richmond",
  "Prince's Bay",
  "Prospect Heights",
  "Prospect Lefferts Gardens",
  "Prospect Park South",
  "Queens Village",
  "Queensboro Hill",
  "Randall Manor",
  "Ravenswood",
  "Red Hook",
  "Rego Park",
  "Remsen Village",
  "Richmond Hill",
  "Richmond Town",
  "Richmond Valley",
  "Ridgewood",
  "Riverdale",
  "Rochdale",
  "Rockaway Park",
  "Roosevelt Island",
  "Rosebank",
  "Rosedale",
  "Rossville",
  "Roxbury",
  "Rugby",
  "Schuylerville",
  "Sea Gate",
  "Seaside",
  "Sheepshead Bay",
  "Silver Lake",
  "SoHo",
  "Somerville",
  "Soundview",
  "South Beach",
  "South Corona",
  "South Jamaica",
  "South Ozone Park",
  "South Side",
  "South Village",
  "Spring Creek",
  "Springfield Gardens",
  "Spuyten Duyvil",
  "St. Albans",
  "St. George",
  "Stapleton",
  "Starrett City",
  "Steinway",
  "Stuyvesant Heights",
  "Stuyvesant Town",
  "Sunnyside Gardens",
  "Sunnyside",
  "Sunnyside",
  "Sunset Park",
  "Sutton Place",
  "Throgs Neck",
  "Times Square",
  "Todt Hill",
  "Tompkins Park North",
  "Tompkinsville",
  "Tottenville",
  "Travis",
  "Tribeca",
  "Tudor City",
  "Turtle Bay",
  "Union Square",
  "Unionport",
  "University Heights",
  "Upper East Side",
  "Upper West Side",
  "Utopia",
  "Vinegar Hill",
  "Wall Street",
  "Ward Hill",
  "Washington Heights",
  "Weeksville",
  "West Brighton",
  "West Brighton",
  "West Farms",
  "West Village",
  "Westchester Square",
  "Westerleigh",
  "Whitestone",
  "Williamsbridge",
  "Williamsburg",
  "Willowbrook",
  "Windsor Terrace",
  "Wingate",
  "Woodhaven",
  "Woodlawn",
  "Woodrow",
  "Woodside",
  "Yorkville",
];
