export const neighborhoods = [
  "Financial District",
  "Bath Beach",
  "Allerton",
  "Battery Park City",
  "Arverne",
  "Annadale",
  "Bay Ridge",
  "Bathgate",
  "Beekman Place",
  "Astoria",
  "Arden Heights",
  "Bedford Stuyvesant",
  "Baychester",
  "Carnegie Hill",
  "Astoria Heights",
  "Arlington",
  "Bensonhurst",
  "Bedford Park",
  "Chelsea",
  "Auburndale",
  "Arrochar",
  "Bergen Beach",
  "Belmont",
  "Chinatown",
  "Bay Terrace",
  "Bay Terrace",
  "Boerum Hill",
  "Bronxdale",
  "Civic Center",
  "Bayside",
  "Bloomfield",
  "Borough Park",
  "Bronx Park South",
  "Clinton",
  "Bayswater",
  "Bulls Head",
  "Brighton Beach",
  "Bronx River",
  "East Harlem",
  "Beechhurst",
  "Butler Manor",
  "Broadway Junction",
  "Castle Hill",
  "East Village",
  "Bellaire",
  "Castleton Corners",
  "Brooklyn Heights",
  "City Island",
  "Financial District",
  "Belle Harbor",
  "Charleston",
  "Brownsville",
  "Claremont Village",
  "Flatiron",
  "Bellerose",
  "Chelsea",
  "Bushwick",
  "Clason Point",
  "Gramercy",
  "Blissville",
  "Clifton",
  "Canarsie",
  "Concourse",
  "Greenwich Village",
  "Breezy Point",
  "Concord",
  "Carroll Gardens",
  "Concourse Village",
  "Hamilton Heights",
  "Briarwood",
  "Dongan Hills",
  "City Line",
  "Co-op City",
  "Harlem (Central)",
  "Broad Channel",
  "Egbertville",
  "Clinton Hill",
  "Country Club",
  "Herald Square",
  "Brookville",
  "Elm Park",
  "Cobble Hill",
  "East Tremont",
  "Hudson Square",
  "Cambria Heights",
  "Eltingville",
  "Coney Island",
  "Eastchester",
  "Inwood",
  "Clearview",
  "Emerson Hill",
  "Crown Heights",
  "Edenwald",
  "Lenox Hill",
  "College Point",
  "Fox Hills",
  "Cypress Hills",
  "Edgewater Park",
  "Lincoln Square",
  "Douglaston",
  "Graniteville",
  "Ditmas Park",
  "Fieldston",
  "Little Italy",
  "Dutch Kills",
  "Grant City",
  "Downtown",
  "Fordham",
  "Lower East Side",
  "East Elmhurst",
  "Grasmere",
  "DUMBO",
  "High Bridge",
  "Manhattan Valley",
  "Edgemere",
  "Great Kills",
  "Dyker Heights",
  "Hunts Point",
  "Manhattanville",
  "Elmhurst",
  "Greenridge",
  "East Flatbush",
  "Kingsbridge",
  "Midtown South",
  "Far Rockaway",
  "Grymes Hill",
  "East New York",
  "Kingsbridge Heights",
  "Midtown",
  "Floral Park",
  "Heartland Village",
  "East Williamsburg",
  "Longwood",
  "Morningside Heights",
  "Flushing",
  "Howland Hook",
  "Farragut",
  "Marble Hill",
  "Murray Hill",
  "Flushing (Downtown)",
  "Huguenot",
  "Flatbush",
  "Melrose",
  "NoHo",
  "Forest Hills",
  "Lighthouse Hill",
  "Flatlands",
  "Morris Heights",
  "Roosevelt Island",
  "Forest Hills Gardens",
  "Livingston",
  "Fort Greene",
  "Morris Park",
  "SoHo",
  "Fresh Meadows",
  "Manor Heights",
  "Fort Hamilton",
  "Morrisania",
  "South Village",
  "Glen Oaks",
  "Mariner's Harbor",
  "Fulton Ferry",
  "Mott Haven",
  "Stuyvesant Town",
  "Glendale",
  "Midland Beach",
  "Georgetown",
  "Mount Eden",
  "Sutton Place",
  "Hammels",
  "New Brighton",
  "Gerritsen Beach",
  "Mount Hope",
  "Times Square",
  "Hillcrest",
  "New Dorp",
  "Gowanus",
  "North Riverdale",
  "Tribeca",
  "Hollis",
  "New Dorp Beach",
  "Gravesend",
  "Norwood",
  "Tudor City",
  "Holliswood",
  "New Springville",
  "Greenpoint",
  "Olinville",
  "Turtle Bay",
  "Howard Beach",
  "Oakwood",
  "Highland Park",
  "Parkchester",
  "Union Square",
  "Hunters Point",
  "Old Place",
  "Homecrest",
  "Pelham Bay",
  "Upper East Side",
  "Jackson Heights",
  "Old Town",
  "Kensington",
  "Pelham Gardens",
  "Upper West Side",
  "Jamaica",
  "Park Hill",
  "Kings Highway",
  "Pelham Parkway",
  "Wall Street",
  "Jamaica Center",
  "Pleasant Plains",
  "Manhattan Beach",
  "Port Morris",
  "Washington Heights",
  "Jamaica Estates",
  "Port Ivory",
  "Manhattan Terrace",
  "Riverdale",
  "West Village",
  "Jamaica Hills",
  "Port Richmond",
  "Mapleton",
  "Schuylerville",
  "Yorkville",
  "Kew Gardens",
  "Prince's Bay",
  "Marine Park",
  "Soundview",
  "Kew Gardens Hills",
  "Randall Manor",
  "Midwood",
  "Spuyten Duyvil",
  "Laurelton",
  "Richmond Town",
  "Mill Basin",
  "Throgs Neck",
  "Lefrak City",
  "Richmond Valley",
  "Mill Island",
  "Unionport",
  "Lindenwood",
  "Rosebank",
  "Navy Yard",
  "University Heights",
  "Little Neck",
  "Rossville",
  "Ocean Hill",
  "West Farms",
  "Maspeth",
  "Silver Lake",
  "Ocean Parkway",
  "Westchester Square",
  "Middle Village",
  "South Beach",
  "Paerdegat Basin",
  "Williamsbridge",
  "Murray Hill",
  "St. George",
  "Park Slope",
  "Woodlawn",
  "Neponsit",
  "Stapleton",
  "Plum Beach",
  "New Hyde Park",
  "Sunnyside",
  "Prospect Heights",
  "North Corona",
  "Todt Hill",
  "Prospect Lefferts Gardens",
  "Oakland Gardens",
  "Tompkinsville",
  "Prospect Park South",
  "Ozone Park",
  "Tottenville",
  "Red Hook",
  "Pomonok",
  "Travis",
  "Remsen Village",
  "Queens Village",
  "Ward Hill",
  "Rugby",
  "Queensboro Hill",
  "West Brighton",
  "Sea Gate",
  "Ravenswood",
  "Westerleigh",
  "Sheepshead Bay",
  "Rego Park",
  "Willowbrook",
  "South Side",
  "Richmond Hill",
  "Woodrow",
  "Spring Creek",
  "Ridgewood",
  "Starrett City",
  "Rochdale",
  "Stuyvesant Heights",
  "Rockaway Park",
  "Sunset Park",
  "Rosedale",
  "Tompkins Park North",
  "Roxbury",
  "Vinegar Hill",
  "Seaside",
  "Weeksville",
  "Somerville",
  "West Brighton",
  "South Corona",
  "Williamsburg",
  "South Jamaica",
  "Windsor Terrace",
  "South Ozone Park",
  "Wingate",
  "Springfield Gardens",
  "St. Albans",
  "Steinway",
  "Sunnyside",
  "Sunnyside Gardens",
  "Utopia",
  "Whitestone",
  "Woodhaven",
  "Woodside",
];
